config/routes.rb
Blitter::Application.routes.draw do
  resources :bleats

  authenticated :user do
    root :to => 'bleats#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show
  match "/images/uploads/*path" => "gridfs#serve"
end

app/models/bleat.rb
class Bleat
  include Mongoid::Document
  include Mongoid::Timestamps
  field :body, :type => String
  field :author, :type => String

  belongs_to :user
end

app/models/user.rb
require 'carrierwave/mongoid'

class User
  include Mongoid::Document

  field :_id, :type => String
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  field :name
  validates_presence_of :name
  validates_format_of :name, :with => /\A\w+\Z/, :on => :create
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :image
  attr_accessible :file

  mount_uploader :image, ImageUploader

  has_many :bleats

  def get_avatar_url
    image.url || "/img/blittie.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :bleat_it

  def bleat_it
    @bleat = Bleat.new
  end
end

app/controllers/bleats_controller.rb
class BleatsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  # GET /bleats
  # GET /bleats.json
  def index
    @bleats = Bleat.desc(:created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bleats }
    end
  end

  # GET /bleats/1
  # GET /bleats/1.json
  def show
    @bleat = Bleat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bleat }
    end
  end

  # GET /bleats/new
  # GET /bleats/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bleat }
    end
  end


  # POST /bleats
  # POST /bleats.json
  def create
    @bleat = current_user.bleats.new(params[:bleat].merge(:author => current_user.name))

    respond_to do |format|
      if @bleat.save
        format.html { redirect_to bleats_url , notice: 'Bleat was successfully created.' }
        format.json { render json: @bleat, status: :created, location: @bleat }
      else
        format.html { render action: "new" }
        format.json { render json: @bleat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bleats/1
  # DELETE /bleats/1.json
  def destroy
    @bleat = current_user.bleats.find(params[:id])
    @bleat.destroy

    respond_to do |format|
      format.html { redirect_to bleats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gridfs_controller.rb
require 'mongo'

class GridfsController < ActionController::Metal
  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")
    begin
      puts Mongoid.database.name
      puts
      puts
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bleats_helper.rb
module BleatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bleats/_form.html.haml
= form_for @bleat do |f|
  -if @bleat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bleat.errors.count, "error")} prohibited this bleat from being saved:"
      %ul
        - @bleat.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :body
    = f.text_field :body
  .actions
    = f.submit 'Save'

app/views/bleats/edit.html.haml
%h1 Editing bleat

= render 'form'

= link_to 'Show', @bleat
\|
= link_to 'Back', bleats_path

app/views/bleats/index.html.haml
%h1 Bleats
- @bleats.each do |bleat|
  .well.row
    .span1= image_tag bleat.user.get_avatar_url, :width => 60
    %h3= link_to  ">#{bleat.author}", "/users/#{bleat.user_id}"
    .bleat= bleat.body

= link_to 'New Bleat', new_bleat_path

app/views/bleats/new.html.haml
%h1 New bleat

= render 'form'

= link_to 'Back', bleats_path

app/views/bleats/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @bleat.body

= link_to 'Edit', edit_bleat_path(@bleat)
\|
= link_to 'Back', bleats_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/layouts/_navigation.html.haml
= link_to "Blitter", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Blitter"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            - if user_signed_in?
              .span4
                .profile
                %ul.nav.nav-list
                  %li
                    = render 'bleats/form'
                  %li.nav-header
                    = image_tag current_user.get_avatar_url, :width => 80, :style => 'float:left'
                    %h2= link_to ">#{current_user.name}", current_user
            %div{:class => "#{(user_signed_in? && 'span8') || 'span12'}"}
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}